# Generated by Django 2.2.17 on 2020-11-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('call', '0002_remove_phone_placecall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placecall', models.ManyToManyField(related_name='call_placecall', to='call.Phone')),
            ],
        ),
    ]
