# Generated by Django 2.2.17 on 2020-11-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='callorigin',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='history',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
